// oxlint-disable no-unused-vars typescript/ban-ts-comment import/consistent-type-specifier-style import/newline-after-import typescript/consistent-type-definitions
// @ts-nocheck
// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


/**
 * Frontend-facing Issue contract for rendering the Issue List and future Issue Detail.
 */
export type Issue = { id: string; title: string; status: string; priority: number; type: string; description: string; comments: IssueComment[]; closeReason: string; assignee: string; labels: string[]; parent: string; blockedBy: string[]; blocks: string[]; created: string; updatedAt: string; closedAt: string; deferUntil: string; due: string }

/**
 * Frontend-facing Issue comment contract.
 */
export type IssueComment = { text: string; author: string; timestamp: string }

/**
 * User-displayable typed issue-list error payload.
 */
export type IssueListError = {
/**
 * Machine-readable error kind.
 */
kind: IssueListErrorKind; message: string }

/**
 * Machine-readable issue-list error kind.
 */
export type IssueListErrorKind = "missingBinary" | "notBeadworkWorkspace" | "commandFailed" | "parseFailed" | "executionFailed"

/**
 * Successful issue-list RPC payload.
 */
export type ListIssuesResponse = { workspacePath: string; issues: Issue[] }

/**
 * Successful Issue Explorer RPC payload containing Beadwork-authored base views.
 */
export type LoadIssueExplorerDataResponse = { workspacePath: string; allIssues: Issue[]; readyIssues: Issue[]; blockedIssues: Issue[] }

/**
 * A workspace known to Beadsmith, represented by its Git root.
 */
export type Workspace = { path: string; availability?: WorkspaceAvailability }

/**
 * Whether a catalog entry was last reachable during startup restoration.
 * This is intentionally distinct from catalog storage health: an unavailable
 * repository remains a recoverable local catalog entry.
 */
export type WorkspaceAvailability = "available" | "unavailable"

/**
 * A typed workspace failure suitable for a later RPC/UI boundary.
 */
export type WorkspaceError = { kind: WorkspaceErrorKind; message: string; retryable: boolean }

/**
 * A typed machine-readable workspace failure category.
 */
export type WorkspaceErrorKind = "storeReadFailed" | "storeSaveFailed" | "validationFailed" | "gitRootFailed" | "loadFailed" | "staleGeneration"

/**
 * Public, serializable workspace state for a later typed RPC boundary.
 */
export type WorkspaceState = { version: number; catalog: Workspace[]; currentWorkspace: Workspace | null; pendingWorkspace: Workspace | null; generation: number; error: WorkspaceError | null }

/**
 * Result of a successful switch; the frontend receives its complete snapshot
 * only after the service's durable Current commit.
 */
export type WorkspaceSwitchResponse = { state: WorkspaceState; issueData: LoadIssueExplorerDataResponse }

const ARGS_MAP = { '':'{"list_issues":[],"load_issue_explorer_data":[],"remove_workspace":["path"],"reset_workspace_memory":[],"retry_workspace_memory":[],"switch_workspace":["candidate_path"],"workspace_state":[]}', 'devBridge':'{"result":["id","value"]}' }
export type Router = { "": {list_issues: () => Promise<ListIssuesResponse>,
load_issue_explorer_data: () => Promise<LoadIssueExplorerDataResponse>,
remove_workspace: (path: string) => Promise<WorkspaceState>,
reset_workspace_memory: () => Promise<WorkspaceState>,
retry_workspace_memory: () => Promise<WorkspaceState>,
switch_workspace: (candidatePath: string) => Promise<WorkspaceSwitchResponse>,
workspace_state: () => Promise<WorkspaceState>},
"devBridge": {result: (id: string, value: string) => Promise<void>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
