// oxlint-disable no-unused-vars typescript/ban-ts-comment import/consistent-type-specifier-style import/newline-after-import typescript/consistent-type-definitions
// @ts-nocheck
// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


/**
 * User-facing Beadsmith settings.
 */
export type AppSettings = { markdown: MarkdownSettings }

/**
 * A typed update failure returned through the RPC boundary.
 */
export type AppSettingsError = { kind: AppSettingsErrorKind; message: string }

/**
 * Shared machine-readable category for load warnings and update errors.
 */
export type AppSettingsErrorKind = "invalidValue" | "malformed" | "unsupportedVersion" | "storeReadFailed" | "storeSaveFailed"

/**
 * Settings plus an optional load warning so the UI can fall back and offer repair.
 */
export type AppSettingsState = { settings: AppSettings; warning: AppSettingsWarning | null }

/**
 * Loose request representation for `update_app_settings`. It accepts any JSON
 * type for `fontSizePx` so the service validator can return the typed
 * `AppSettingsError` for fractional, out-of-range, and wrong-type input instead
 * of leaving callers with an argument-decoding failure.
 */
export type AppSettingsUpdate = { markdown: MarkdownSettingsUpdate }

export type AppSettingsWarning = { kind: AppSettingsErrorKind; message: string }

/**
 * Frontend-facing Issue contract for rendering the Issue List and future Issue Detail.
 */
export type Issue = { id: string; title: string; status: string; priority: number; type: string; description: string; comments: IssueComment[]; closeReason: string; assignee: string; labels: string[]; parent: string; blockedBy: string[]; blocks: string[]; created: string; updatedAt: string; closedAt: string; deferUntil: string; due: string }

/**
 * Frontend-facing Issue comment contract.
 */
export type IssueComment = { text: string; author: string; timestamp: string }

/**
 * User-displayable typed issue-list error payload.
 */
export type IssueListError = {
/**
 * Machine-readable error kind.
 */
kind: IssueListErrorKind; message: string }

/**
 * Machine-readable issue-list error kind.
 */
export type IssueListErrorKind = "missingBinary" | "notBeadworkWorkspace" | "commandFailed" | "parseFailed" | "executionFailed"

export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>

/**
 * Successful issue-list RPC payload.
 */
export type ListIssuesResponse = { workspacePath: string; issues: Issue[] }

/**
 * Successful Issue Explorer RPC payload containing Beadwork-authored base views.
 */
export type LoadIssueExplorerDataResponse = { workspacePath: string; allIssues: Issue[]; readyIssues: Issue[]; blockedIssues: Issue[] }

export type MarkdownSettings = { fontSizePx: number }

export type MarkdownSettingsUpdate = { fontSizePx: JsonValue }

/**
 * A workspace known to Beadsmith, represented by its Git root.
 */
export type Workspace = { path: string; availability?: WorkspaceAvailability }

/**
 * Whether a catalog entry was last reachable during startup restoration.
 * This is intentionally distinct from catalog storage health: an unavailable
 * repository remains a recoverable local catalog entry.
 */
export type WorkspaceAvailability = "available" | "unavailable"

/**
 * Result of a `cancel_workspace` call. The state mirrors what a normal
 * in-flight cancel would publish; the optional `issue_data` is set only
 * when the cancel arrives after the durable commit has already cleared
 * the in-flight pending request but before its success publication has
 * reached the renderer. In that race window, pairing the matching Issue
 * Explorer snapshot with the new state keeps the renderer from briefly
 * rendering a Current Workspace identity without its corresponding
 * snapshot. A real Pending cancellation that was cleared by Cancel
 * itself never carries `issue_data`: leaving the prior workspace's
 * issue list untouched is the desired outcome.
 */
export type WorkspaceCancelResponse = { state: WorkspaceState; issueData: LoadIssueExplorerDataResponse | null }

/**
 * A typed workspace failure suitable for a later RPC/UI boundary.
 */
export type WorkspaceError = { kind: WorkspaceErrorKind; message: string; retryable: boolean }

/**
 * A typed machine-readable workspace failure category.
 */
export type WorkspaceErrorKind = "storeReadFailed" | "storeSaveFailed" | "validationFailed" | "gitRootFailed" | "loadFailed" | "staleGeneration"

/**
 * Result of a successful startup-memory retry; the frontend receives its
 * complete snapshot only when the remembered Current was restored and
 * validated through the normal selection transaction. `issue_data` is `None`
 * when nothing was restored (no remembered Current or restore failed).
 */
export type WorkspaceRetryMemoryResponse = { state: WorkspaceState; issueData: LoadIssueExplorerDataResponse | null }

/**
 * Public, serializable workspace state for a later typed RPC boundary.
 */
export type WorkspaceState = { version: number; catalog: Workspace[]; currentWorkspace: Workspace | null; pendingWorkspace: Workspace | null;
/**
 * Ephemeral retry target surfaced when a post-validation switch attempt
 * fails (load or final save). It is the validated candidate that the UI's
 * Retry banner must replay. Cleared on new selection, cancel, removal,
 * reset, and successful commit. Never persisted: durable retry state
 * would let a saved failure look active after restart.
 */
retryWorkspace: Workspace | null; generation: number; error: WorkspaceError | null }

/**
 * Result of a successful switch; the frontend receives its complete snapshot
 * only after the service's durable Current commit.
 */
export type WorkspaceSwitchResponse = { state: WorkspaceState; issueData: LoadIssueExplorerDataResponse }

const ARGS_MAP = { '':'{"app_settings_state":[],"cancel_workspace":[],"list_issues":[],"load_issue_explorer_data":[],"remove_workspace":["path"],"reset_workspace_memory":[],"retry_workspace_memory":[],"switch_workspace":["candidate_path"],"update_app_settings":["settings"],"workspace_state":[]}', 'devBridge':'{"result":["id","value"]}' }
export type Router = { "": {app_settings_state: () => Promise<AppSettingsState>,
cancel_workspace: () => Promise<WorkspaceCancelResponse>,
list_issues: () => Promise<ListIssuesResponse>,
load_issue_explorer_data: () => Promise<LoadIssueExplorerDataResponse>,
remove_workspace: (path: string) => Promise<WorkspaceState>,
reset_workspace_memory: () => Promise<WorkspaceState>,
retry_workspace_memory: () => Promise<WorkspaceRetryMemoryResponse>,
switch_workspace: (candidatePath: string) => Promise<WorkspaceSwitchResponse>,
update_app_settings: (settings: AppSettingsUpdate) => Promise<AppSettings>,
workspace_state: () => Promise<WorkspaceState>},
"devBridge": {result: (id: string, value: string) => Promise<void>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
