// oxlint-disable no-unused-vars typescript/ban-ts-comment import/consistent-type-specifier-style import/newline-after-import typescript/consistent-type-definitions
// @ts-nocheck
// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


/**
 * Frontend-facing Issue contract for rendering the Issue List and future Issue Detail.
 */
export type Issue = { id: string; title: string; status: string; priority: number; type: string; description: string; comments: IssueComment[]; closeReason: string; assignee: string; labels: string[]; parent: string; blockedBy: string[]; blocks: string[]; created: string; updatedAt: string; closedAt: string; deferUntil: string; due: string }

/**
 * Frontend-facing Issue comment contract.
 */
export type IssueComment = { text: string; author: string; timestamp: string }

/**
 * User-displayable typed issue-list error payload.
 */
export type IssueListError = { 
/**
 * Machine-readable error kind.
 */
kind: IssueListErrorKind; message: string }

/**
 * Machine-readable issue-list error kind.
 */
export type IssueListErrorKind = "missingBinary" | "notBeadworkWorkspace" | "commandFailed" | "parseFailed" | "executionFailed"

/**
 * Successful issue-list RPC payload.
 */
export type ListIssuesResponse = { workspacePath: string; issues: Issue[] }

const ARGS_MAP = { '':'{"list_issues":[]}', 'devBridge':'{"result":["id","value"]}' }
export type Router = { "": {list_issues: () => Promise<ListIssuesResponse>},
"devBridge": {result: (id: string, value: string) => Promise<void>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
